// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMmiBPXsaBc-GBZCWQttIyWIIdSDhATfM',
    appId: '1:402895983316:android:894eb3951a65eb9b19e141',
    messagingSenderId: '402895983316',
    projectId: 'dbtrials',
    databaseURL: 'https://dbtrials-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dbtrials.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc6Gg3ocxYmhOSGd1GWJ_YNt01stNC0uo',
    appId: '1:402895983316:ios:67c624aa4f17698319e141',
    messagingSenderId: '402895983316',
    projectId: 'dbtrials',
    databaseURL: 'https://dbtrials-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dbtrials.appspot.com',
    iosClientId: '402895983316-g363qtc7asd3hqvtf0mgpchfgcgkc3rk.apps.googleusercontent.com',
    iosBundleId: 'com.example.roadmonitoring',
  );
}
